//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Bussines
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDanhSachTrucBan
    {
        public string ThuTu { get; set; }
        public string HoVaTen { get; set; }
        public string CapBac { get; set; }
        public string ChucVu { get; set; }
        public string GioTu { get; set; }
        public string GioDen { get; set; }
        public System.DateTime ThoiGianTu { get; set; }
        public System.DateTime ThoiGianDen { get; set; }
        public string NguoiNhapMay { get; set; }
        public Nullable<System.DateTime> NgayNhapMay { get; set; }
        public string HinhThucTruc { get; set; }
        public string DonVi { get; set; }
    }
}
