//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Bussines
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLichLamViec
    {
        public string NguoiTruc { get; set; }
        public string MoTaTrucCaNgay { get; set; }
        public string MoTaTrucBuoiSang { get; set; }
        public string MoTaTrucBuoiChieu { get; set; }
        public string GioTrucSang { get; set; }
        public string GioTrucChieu { get; set; }
        public string GioTrucCaNgay { get; set; }
        public string TrucCaNgay { get; set; }
        public System.DateTime NgayTruc { get; set; }
        public string NguoiNhapMay { get; set; }
        public Nullable<System.DateTime> NgayNhapMay { get; set; }
    }
}
