//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Bussines
{
    using System;
    using System.Collections.Generic;
    
    public partial class TThongTinLichTruc
    {
        public string MaTongHopTruc { get; set; }
        public string MoTaTongHopTruc { get; set; }
        public System.DateTime TrucTuNgay { get; set; }
        public System.DateTime TrucDenNgay { get; set; }
        public string NguoiNhapMay { get; set; }
        public Nullable<System.DateTime> NgayNhapMay { get; set; }
    }
}
