//===========================================
// MVC# Framework | www.MVCSharp.org        |
// ------------------------------------------
// Copyright (C) 2008 www.MVCSharp.org      |
// All rights reserved.                     |
//===========================================

using System;
using System.Text;

namespace MVCSharp.Core.Configuration.Views
{
    #region Documentation
    /// <summary>
    /// ViewInfo objects are used by views managers for view creation
    /// and activation. Base ViewInfo objects contain only information
    /// on view type (<see cref="ViewType"/> property), whereas different
    /// ViewInfo subclasses define properties specific to the corresponding
    /// presentation platforms.
    /// </summary>
    /// <remarks>
    /// It is unlikely you will need to manually create ViewInfo objects.
    /// Typically they are generated by the framework from <see cref="ViewAttribute"/>
    /// and derived attributes.
    /// </remarks>
    /// <seealso cref="ViewAttribute"/>
    #endregion
    public class ViewInfo
    {
        private Type viewType;

        #region Documentation
        /// <summary>
        /// ViewInfo constructor. Creates ViewInfo object with specified
        /// ViewType value.
        /// </summary>
        #endregion
        public ViewInfo(Type viewType)
        {
            ViewType = viewType;
        }

        #region Documentation
        /// <summary>
        /// Defines view type as a part of a view description.
        /// </summary>
        #endregion
        public Type ViewType
        {
            get { return viewType; }
            set { viewType = value; }
        }
    }
}
