export const LOAD_MENU = 'LOAD_MENU';
export const COMPUTE_SELECTED_MENU = 'COMPUTE_SELECTED_MENU';
export const LOAD_LEFT_COLUMN = 'LOAD_LEFT_COLUMN';
export const CHANGE_LEFT_COLUMN_FILTER = 'CHANGE_LEFT_COLUMN_FILTER';
export const LEFT_COLUMN_BY_USER = 'LEFT_COLUMN_BY_USER';
export const LEFT_COLUMN_ADD_REPORTED_FILTER = 'LEFT_COLUMN_ADD_REPORTED_FILTER';
export const SET_SELECTED_THREAD = 'SET_SELECTED_THREAD';

export const GO_TO_PAGE_LEFT_COLUMN = 'GO_TO_PAGE_LEFT_COLUMN';
export const LOAD_THREAD = 'LOAD_THREAD';
export const NEW_THREAD = 'NEW_THREAD';
export const SAVE_NEW_THREAD = 'SAVE_NEW_THREAD';
export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export const LOAD_USER_PROFILE_FAILURE = 'LOAD_USER_PROFILE_FAILURE';
export const LOAD_CREDENTIALS = 'LOAD_CREDENTIALS';
export const LOAD_USER_RIGHTS = 'LOAD_USER_RIGHTS';
export const LOAD_FOOTER_TOP_DAY = 'LOAD_FOOTER_TOP_DAY';
export const LOAD_FOOTER_TOP_WEEK = 'LOAD_FOOTER_TOP_WEEK';
export const LOAD_FOOTER_STATISTIC = 'LOAD_FOOTER_STATISTIC';
export const LOAD_CURRENT_MAIN_TOPIC = 'LOAD_CURRENT_MAIN_TOPIC';
export const CHANGE_SORT_COMMENTS = 'CHANGE_SORT_COMMENTS';
export const ADJUST_APP_BODY_HEIGHT = 'ADJUST_APP_BODY_HEIGHT';
export const SCROLL_TO_MIDDLE_COLUMN = 'SCROLL_TO_MIDDLE_COLUMN';
export const REPORT_CONTENT = 'REPORT_CONTENT';
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT';
export const FOLLOW_THREAD = 'FOLLOW_THREAD';
export const UNFOLLOW_THREAD = 'UNFOLLOW_THREAD';

export const LOAD_STATISTIC = 'LOAD_STATISTIC';

export const LOAD_USER_SETTINGS = 'LOAD_USER_SETTINGS';
export const LOAD_USER_SETTINGS_FAILURE = 'LOAD_USER_SETTINGS_FAILURE';
export const SAVE_USER_SETTINGS_SUCCESS = 'SAVE_USER_SETTINGS_SUCCESS';
export const SAVE_USER_SETTINGS_FAILURE = 'SAVE_USER_SETTINGS_FAILURE';
export const LOAD_USER_FAVORITES = 'LOAD_USER_FAVORITES';
export const ADD_USER_FAVORITES_SUCCESS = 'ADD_USER_FAVORITES_SUCCESS';
export const ADD_USER_FAVORITES_FAILURE = 'ADD_USER_FAVORITES_FAILURE';
export const REMOVE_USER_FAVORITES_SUCCESS = 'REMOVE_USER_FAVORITES_SUCCESS';
export const REMOVE_USER_FAVORITES_FAILURE = 'REMOVE_USER_FAVORITES_FAILURE';
export const LOAD_USER_IGNORES = 'LOAD_USER_IGNORES';
export const ADD_USER_IGNORES_SUCCESS = 'ADD_USER_IGNORES_SUCCESS';
export const ADD_USER_IGNORES_FAILURE = 'ADD_USER_IGNORES_FAILURE';
export const REMOVE_USER_IGNORES_SUCCESS = 'REMOVE_USER_IGNORES_SUCCESS';
export const REMOVE_USER_IGNORES_FAILURE = 'REMOVE_USER_IGNORES_FAILURE';

export const LOAD_SEARCH_SUGGESTION = 'LOAD_SEARCH_SUGGESTION';
export const LOAD_SEARCH_CLEAR_SUGGESTION = 'LOAD_SEARCH_CLEAR_SUGGESTION';
export const LOAD_SEARCH_EXECUTE = 'LOAD_SEARCH_EXECUTE';
export const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER';

export const LOADING_MAIN_COLUMN = 'LOADING_MAIN_COLUMN';
export const LOADED_MAIN_COLUMN = 'LOADED_MAIN_COLUMN';
export const LOADING_LEFT_COLUMN = 'LOADING_LEFT_COLUMN';
export const LOADED_LEFT_COLUMN = 'LOADED_LEFT_COLUMN';
export const LOADING_TYPE2_MAIN_COLUMN = 'LOADING_TYPE2_MAIN_COLUMN';
export const LOADED_TYPE2_MAIN_COLUMN = 'LOADED_TYPE2_MAIN_COLUMN';

export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL';

export const ADMIN_MOVE_THREAD = 'ADMIN_MOVE_THREAD';
export const ADMIN_GET_REPORTED_MESSAGES = 'ADMIN_GET_REPORTED_MESSAGES';

export const LOAD_EMPTY_MAIN_TOPIC = 'LOAD_EMPTY_MAIN_TOPIC';
