export const drinkTypeActionTypes = {
  UPDATE_DRINK_TYPE: 'UPDATE_DRINK_TYPE',
  RESET_DRINK_TYPE: 'RESET_DRINK_TYPE',
  FAILURE: 'FAILURE',
}

export const drinkTemperatureActionTypes = {
  UPDATE_DRINK_TEMPERATURE: 'UPDATE_DRINK_TEMPERATURE',
  RESET_DRINK_TEMPERATURE: 'RESET_DRINK_TEMPERATURE',
  FAILURE: 'FAILURE',
}

export const autoDoseActionTypes = {
  UPDATE_AUTO_DOSE: 'UPDATE_AUTO_DOSE',
  RESET_AUTO_DOSE: 'RESET_AUTO_DOSE',
  FAILURE: 'FAILURE',
}

export const localizationActionTypes = {
  UPDATE_LOCALIZATION: 'UPDATE_LOCALIZATION',
  RESET_LOCALIZATION: 'RESET_LOCALIZATION',
  FAILURE: 'FAILURE',
}

export const loaddingActionTypes = {
  SHOW_LOADDING: 'SHOW_LOADDING',
  HIDE_LOADDING: 'HIDE_LOADDING',
}

export const loginActionTypes = {
  LOGIN_FALSE: 'LOGIN_FALSE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
}

export const historicalActionTypes = {
  UPDATE_HISTORICAL: 'UPDATE_HISTORICAL',
  RESET_HISTORICAL: 'RESET_HISTORICAL',
  FAILURE: 'FAILURE',
}

export const userPermissionActionTypes = {
  UPDATE_USER_PERMISSION: 'UPDATE_USER_PERMISSION',
  RESET_USER_PERMISSION: 'RESET_USER_PERMISSION',
  FAILURE: 'FAILURE',
}
